// export const LOGIN_USER_REQUEST="LOGIN_USER_REQUEST";
// export const LOGIN_USER_SUCESS="LOGIN_USER_SUCESS";
// export const LOGIN_USER_FAILURE="LOGIN_USER_FAILURE";

// export const REGISTER_USER_REQUEST="REGISTER_USER_REQUEST";
// export const REGISTER_USER_SUCESS="REGISTER_USER_SUCESS";
// export const REGISTER_USER_FAILURE="REGISTER_USER_FAILURE";

// export const GET_USER_PROFILE_REQUEST="GET_USER_PROFILE_REQUEST";
// export const GET_USER_PROFILE_SUCESS="GET_USER_PROFILE_SUCESS";
// export const GET_USER_PROFILE_FAILURE="GET_USER_PROFILE_FAILURE";